name: build

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ['3.9']
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools
          pip install -r requirements_dev.txt
      
      - shell: bash
        run: |
          .github/workflows/setup.sh

      - name: Test with mypy
        run: mypy src tests

      - name: Test with flake8
        run: flake8 src tests

      - name: Test with tox
        run: tox

      - name: Generate coverage report
        run: pytest --cov=./ --cov-report=xml

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}
